menu:
  Home: /
  Archives: /archives
  About: /about

widgets: 
- search
- category
- tag
- twitter

excerpt_link:

github:
  username: aprilorange 

twitter:
  username: aprilorange0
  show_replies: false
  tweet_count: 5

weibo:
  nickname: 四月橘林

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
domain:

rss: